version: "3.7"

services:
    sentry:
        build: ./etc/sentry
        command: run web
        depends_on:
            - postgres
            - redis
        environment:
            SENTRY_SECRET_KEY: secret
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_POSTGRES_PORT: 5432
            SENTRY_DB_NAME: database
            SENTRY_DB_USER: user
            SENTRY_DB_PASSWORD: secret
            SENTRY_REDIS_HOST: redis
            SENTRY_REDIS_PORT: 6379

    sentry-cron:
        build: ./etc/sentry
        command: run cron
        depends_on:
            - postgres
            - redis
        environment:
            SENTRY_SECRET_KEY: secret
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_POSTGRES_PORT: 5432
            SENTRY_DB_NAME: database
            SENTRY_DB_USER: user
            SENTRY_DB_PASSWORD: secret
            SENTRY_REDIS_HOST: redis
            SENTRY_REDIS_PORT: 6379

    sentry-worker:
        build: ./etc/sentry
        command: run worker
        depends_on:
            - postgres
            - redis
        environment:
            SENTRY_SECRET_KEY: secret
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_POSTGRES_PORT: 5432
            SENTRY_DB_NAME: database
            SENTRY_DB_USER: user
            SENTRY_DB_PASSWORD: secret
            SENTRY_REDIS_HOST: redis
            SENTRY_REDIS_PORT: 6379

    redis:
        image: redis:5.0

    postgres:
        image: postgres:11.1
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: database
